from __future__ import annotations

import asyncio
import json
import logging
import os
import re
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from urllib.parse import parse_qs, urlencode, urlparse

import httpx
import trafilatura
from datasketch import MinHash
from dotenv import load_dotenv
from rapidfuzz import fuzz
from tavily import TavilyClient

from .cache import get_cache, fetch_cache_key, search_cache_key
from .schemas import Plan, Source, SourcesOutput

load_dotenv()

logger = logging.getLogger(__name__)

OUTPUTS_DIR = Path(__file__).parent.parent / "outputs"

# ---------------------------------------------------------------------------
# Domain credibility table (loaded once at import time)
# ---------------------------------------------------------------------------

_CRED_PATH = Path(__file__).parent / "domain_credibility.json"
_CRED_DATA = json.loads(_CRED_PATH.read_text(encoding="utf-8"))

_PLATFORM_DOMAINS: set[str] = set(_CRED_DATA["platform_domains"])
_BLOCKLIST_DOMAINS: set[str] = set(_CRED_DATA["blocklist_domains"])
_SUBDOMAIN_OVERRIDES: dict[str, str] = _CRED_DATA.get("subdomain_overrides", {})

# Flat domain → tier lookup built from the tiers dict
_DOMAIN_TIER: dict[str, str] = {}
for _tier_name, _domains in _CRED_DATA["tiers"].items():
    for _d in _domains:
        _DOMAIN_TIER[_d] = _tier_name


# ---------------------------------------------------------------------------
# Domain helpers (used across all subtasks)
# ---------------------------------------------------------------------------

def extract_domain(url: str) -> str:
    """Return bare domain, stripping www."""
    return urlparse(url).netloc.removeprefix("www.")


def get_domain_tier(domain: str) -> str:
    """Return credibility tier. Subdomain overrides take precedence over the main tier table."""
    if domain in _SUBDOMAIN_OVERRIDES:
        return _SUBDOMAIN_OVERRIDES[domain]
    return _DOMAIN_TIER.get(domain, "tier_3_media")


def is_platform(domain: str) -> bool:
    return domain in _PLATFORM_DOMAINS


def is_blocklisted(domain: str) -> bool:
    return domain in _BLOCKLIST_DOMAINS


def is_media_outlet(domain: str) -> bool:
    """Return True if domain is a known media outlet (listed in any credibility tier)."""
    return domain in _DOMAIN_TIER


# Matches non-English locale path segments: /zh-hans-cn/, /ru-ru/, /pl-pl/, etc.
_I18N_RE = re.compile(r"/([a-z]{2}-[a-z]{2,}(?:-[a-z]{2,})?)/")


def is_non_english_i18n(url: str) -> bool:
    """Return True if URL is a non-English i18n variant (e.g. /zh-hans-cn/, /ru-ru/)."""
    path = urlparse(url).path.lower()
    m = _I18N_RE.search(path)
    if not m:
        return False
    lang = m.group(1).split("-")[0]
    return lang != "en"


# ---------------------------------------------------------------------------
# Subtask 2 — Tier 1: primary source URL discovery
# ---------------------------------------------------------------------------

def _tier1_credibility(domain: str) -> str:
    if domain in _SUBDOMAIN_OVERRIDES:
        return _SUBDOMAIN_OVERRIDES[domain]
    return "primary_disputed" if is_blocklisted(domain) else "primary"


# Standard primary document patterns per event type.
# These supplement Stage A's queries to ensure canonical primary documents
# (system cards, schedules, brackets, official programs) are always targeted.
_PRIMARY_DOC_PATTERNS: dict[str, list[str]] = {
    "product_launch":  ["system card", "release notes"],
    "sports_event":    ["official schedule", "bracket", "squad list"],
    "scheduled_event": ["official program", "schedule", "lineup"],
    "live_event":      ["official program", "running order"],
}


def _tier1_queries(plan: Plan) -> list[tuple[str, str]]:
    """
    Build (query, domain) pairs for Tier 1 discovery.

    Priority order:
    1. site: queries already generated by Stage A (most specific)
    2. Fallback: site:<domain> <normalized_title> for any candidate not yet covered
    3. Supplementary: per-event-type document pattern queries (system card, schedule, etc.)
    """
    queries: list[tuple[str, str]] = []
    seen_queries: set[str] = set()

    def _add(q: str, domain: str) -> None:
        if q not in seen_queries:
            queries.append((q, domain))
            seen_queries.add(q)

    # 1. Stage A's own site: queries
    for q in plan.search_queries:
        m = re.search(r"site:(\S+)", q, re.IGNORECASE)
        if m:
            domain = m.group(1).lower().rstrip("/")
            if not is_platform(domain) and not is_media_outlet(domain):
                _add(q, domain)

    # 2 + 3. For each primary candidate: fallback title query + doc-pattern queries
    doc_patterns = _PRIMARY_DOC_PATTERNS.get(plan.event_type, [])
    for raw in plan.primary_source_candidates:
        domain = raw.lower().rstrip("/")
        if is_platform(domain):
            logger.debug("Tier 1 skip (platform): %s", domain)
            continue
        if is_media_outlet(domain):
            logger.info("Tier 1 skip (media outlet, rerouted to Tier 2): %s", domain)
            continue
        # Fallback title query
        _add(f"site:{domain} {plan.normalized_title}", domain)
        # Document-type supplementary queries
        for pattern in doc_patterns:
            _add(f"site:{domain} {pattern}", domain)

    return queries


def discover_tier1_urls(plan: Plan, tavily: TavilyClient) -> list[dict]:
    """
    For each primary source candidate, run a site:-scoped Tavily search to
    find candidate URLs. Returns raw URL metadata dicts; body fetch is subtask 5.
    """
    cache = get_cache()
    results: list[dict] = []

    for query, domain in _tier1_queries(plan):
        cache_key = f"search:{search_cache_key(query, max_results=5, tier=1)}"
        cached = cache.get(cache_key)

        if cached is not None:
            logger.debug("Tier 1 cache hit: %s", query[:60])
            raw = cached
        else:
            try:
                resp = tavily.search(
                    query=query,
                    search_depth="basic",
                    max_results=5,
                )
                raw = resp.get("results", [])
                cache.set(cache_key, raw)
                logger.debug("Tier 1 Tavily search: %s → %d results", query[:60], len(raw))
            except Exception as exc:
                logger.warning("Tier 1 search failed (%s): %s", domain, exc)
                continue

        for r in raw:
            url = r.get("url", "")
            result_domain = extract_domain(url)
            # Keep only URLs that belong to the target domain
            if result_domain != domain and not result_domain.endswith(f".{domain}"):
                continue
            # Drop non-English i18n variants
            if is_non_english_i18n(url):
                logger.debug("Tier 1 skip (non-English i18n): %s", url)
                continue
            results.append({
                "url": url,
                "title": r.get("title", ""),
                "domain": domain,
                "credibility_tier": _tier1_credibility(domain),
                "retrieval_tier": 1,
                "published_at": r.get("published_date"),
            })

    logger.info("Tier 1 discovered %d candidate URL(s)", len(results))
    return results


# ---------------------------------------------------------------------------
# Subtask 3 — Tier 2: general search + domain scoring
# ---------------------------------------------------------------------------

# Tier ordering for sort (lower = higher priority)
_TIER_RANK: dict[str, int] = {
    "primary":          0,
    "primary_disputed": 1,
    "tier_1_media":     2,
    "tier_2_media":     3,
    "tier_3_media":     4,
    "low_quality":      5,
}


def _tier2_queries(plan: Plan) -> list[str]:
    """
    Return search_queries that are NOT site:-scoped.
    These are the broad queries used for Tier 2 general search.
    """
    return [q for q in plan.search_queries if not re.search(r"site:\S+", q, re.IGNORECASE)]


def search_tier2(plan: Plan, tavily: TavilyClient) -> list[dict]:
    # Build a set of primary domains from the plan for credibility upgrade
    _primary_domains = {d.lower().rstrip("/") for d in plan.primary_source_candidates}
    """
    Run broad Tavily searches, score each result against domain_credibility,
    and return deduplicated URL metadata sorted by tier then recency.

    Blocklisted and platform domains are dropped. Results with unknown domains
    default to tier_3_media.
    """
    cache = get_cache()
    seen_urls: set[str] = set()
    raw_results: list[dict] = []

    for query in _tier2_queries(plan):
        cache_key = f"search:{search_cache_key(query, max_results=10, tier=2)}"
        cached = cache.get(cache_key)

        if cached is not None:
            logger.debug("Tier 2 cache hit: %s", query[:60])
            batch = cached
        else:
            try:
                resp = tavily.search(
                    query=query,
                    search_depth="basic",
                    max_results=10,
                )
                batch = resp.get("results", [])
                cache.set(cache_key, batch)
                logger.debug("Tier 2 search: %s → %d results", query[:60], len(batch))
            except Exception as exc:
                logger.warning("Tier 2 search failed (%s): %s", query[:40], exc)
                continue

        for r in batch:
            url = r.get("url", "")
            if not url or url in seen_urls:
                continue

            domain = extract_domain(url)

            if is_platform(domain):
                logger.debug("Tier 2 skip (platform): %s", url)
                continue
            if is_blocklisted(domain):
                logger.debug("Tier 2 skip (blocklist): %s", url)
                continue
            if is_non_english_i18n(url):
                logger.debug("Tier 2 skip (non-English i18n): %s", url)
                continue

            # subdomain_overrides take precedence over everything
            if domain in _SUBDOMAIN_OVERRIDES:
                tier = _SUBDOMAIN_OVERRIDES[domain]
            elif domain in _primary_domains or any(domain.endswith(f".{p}") for p in _primary_domains):
                tier = "primary"
            else:
                tier = get_domain_tier(domain)  # defaults to tier_3_media if unknown
            seen_urls.add(url)
            raw_results.append({
                "url": url,
                "title": r.get("title", ""),
                "domain": domain,
                "credibility_tier": tier,
                "retrieval_tier": 2,
                "published_at": r.get("published_date"),
                "_tier_rank": _TIER_RANK.get(tier, 5),
            })

    # Sort: tier rank ascending, then recency descending (None dates go last)
    raw_results.sort(key=lambda r: (r["_tier_rank"], _date_sort_key(r["published_at"])))
    for r in raw_results:
        del r["_tier_rank"]

    logger.info(
        "Tier 2 found %d URL(s) across %d quer%s",
        len(raw_results),
        len(_tier2_queries(plan)),
        "y" if len(_tier2_queries(plan)) == 1 else "ies",
    )
    return raw_results


# ---------------------------------------------------------------------------
# Subtask 4 — Deterministic filtering layer
# ---------------------------------------------------------------------------

# URL path patterns that indicate non-article pages (tag pages, category indexes, etc.)
_URL_PATH_BLOCKLIST = re.compile(
    r"(/tag/|/tags/|/category/|/categories/"
    r"|/author/|/authors/|/feed/|/rss/"
    r"|/topic/|/topics/|/page/\d+|/search\b)",
    re.IGNORECASE,
)

# URL query-string patterns indicating pagination or aggregation
_URL_QUERY_BLOCKLIST = re.compile(r"[?&](page|p)=\d+", re.IGNORECASE)

# Per-tier source caps applied after deduplication (primary noise filtered by subtask 5 key-entity check)
_PER_TIER_CAPS: dict[str, int] = {
    "primary":          12,
    "primary_disputed":  5,
    "tier_1_media":     10,
    "tier_2_media":     10,
    "tier_3_media":     10,
    "low_quality":       3,
}
_TOTAL_CAP = 25


def _matches_url_blocklist(url: str) -> bool:
    path = urlparse(url).path
    query = urlparse(url).query
    return bool(_URL_PATH_BLOCKLIST.search(path) or _URL_QUERY_BLOCKLIST.search(query))


def _is_gpt_store_url(url: str) -> bool:
    """chatgpt.com/g/<id> paths are third-party GPTs, not official OpenAI content."""
    parsed = urlparse(url)
    return parsed.netloc.removeprefix("www.") == "chatgpt.com" and parsed.path.startswith("/g/")


def _has_non_english_locale_param(url: str) -> bool:
    """Filter URLs with ?locale=xx-XX where language is not English."""
    params = parse_qs(urlparse(url).query)
    locale = params.get("locale", [""])[0].lower()
    if not locale:
        return False
    return locale.split("-")[0] not in ("en", "")


def _parse_partial_date(date_str: str) -> datetime:
    """Parse ISO 8601 partial date (YYYY, YYYY-MM, YYYY-MM-DD) to datetime (UTC)."""
    parts = date_str.split("-")
    try:
        if len(parts) == 1:
            return datetime(int(parts[0]), 1, 1, tzinfo=timezone.utc)
        if len(parts) == 2:
            return datetime(int(parts[0]), int(parts[1]), 1, tzinfo=timezone.utc)
        return datetime.strptime(date_str[:10], "%Y-%m-%d").replace(tzinfo=timezone.utc)
    except ValueError:
        return datetime(2000, 1, 1, tzinfo=timezone.utc)


def _in_time_window(published_at: str, key_date: str, window_days: int) -> bool:
    """Return True if published_at falls within [key_date - window_days, now + 7 days]."""
    try:
        pub = _parse_partial_date(published_at)
        anchor = _parse_partial_date(key_date)
        now = datetime.now(tz=timezone.utc)
        start = anchor - timedelta(days=window_days)
        end = now + timedelta(days=7)
        return start <= pub <= end
    except Exception:
        return True  # if we can't parse, don't filter


def _normalize_url(url: str) -> str:
    """Normalize URL for deduplication: lowercase host, strip trailing slash, remove tracking params."""
    parsed = urlparse(url)
    tracking = {"utm_source", "utm_medium", "utm_campaign", "utm_content", "utm_term", "ref", "source"}
    params = {k: v for k, v in parse_qs(parsed.query).items() if k.lower() not in tracking}
    clean_query = urlencode(params, doseq=True)
    path = parsed.path.rstrip("/") or "/"
    host = parsed.netloc.lower().removeprefix("www.")
    return f"{parsed.scheme}://{host}{path}{'?' + clean_query if clean_query else ''}"


def filter_urls(
    candidates: list[dict],
    plan: "Plan",
    time_window_days: int = 90,
) -> tuple[list[dict], dict]:
    """
    Apply all deterministic filters to URL candidates.
    Returns (kept_list, stats_dict) where stats shows per-rule removal counts.
    URLs without published_at are NOT filtered by time window (kept, fate decided at fetch time).
    """
    stats: dict[str, int] = defaultdict(int)
    stats["input"] = len(candidates)
    seen_norm: set[str] = set()
    kept: list[dict] = []

    for r in candidates:
        url = r.get("url", "")
        domain = r.get("domain") or extract_domain(url)

        if is_blocklisted(domain):
            stats["removed_blocklist"] += 1
            logger.debug("FILTER blocklist      %s", url)
            continue

        if _is_gpt_store_url(url):
            stats["removed_gpt_store"] += 1
            logger.debug("FILTER gpt_store      %s", url)
            continue

        if _matches_url_blocklist(url):
            stats["removed_url_pattern"] += 1
            logger.debug("FILTER url_pattern    %s", url)
            continue

        if is_non_english_i18n(url):
            stats["removed_i18n_path"] += 1
            logger.debug("FILTER i18n_path      %s", url)
            continue

        if _has_non_english_locale_param(url):
            stats["removed_i18n_locale_param"] += 1
            logger.debug("FILTER i18n_param     %s", url)
            continue

        pub = r.get("published_at")
        if pub and not _in_time_window(pub, plan.key_date, time_window_days):
            stats["removed_time_window"] += 1
            logger.debug("FILTER time_window    %s (pub: %s)", url, pub)
            continue

        norm = _normalize_url(url)
        if norm in seen_norm:
            stats["removed_duplicate"] += 1
            logger.debug("FILTER duplicate      %s", url)
            continue
        seen_norm.add(norm)

        kept.append(r)

    # Sort by tier rank + recency before capping so higher-quality sources survive
    kept.sort(key=lambda r: (
        _TIER_RANK.get(r.get("credibility_tier", "tier_3_media"), 5),
        _date_sort_key(r.get("published_at")),
    ))

    # Per-tier caps + total safety cap
    tier_counts: dict[str, int] = defaultdict(int)
    capped: list[dict] = []
    for r in kept:
        tier = r.get("credibility_tier", "tier_3_media")
        if tier_counts[tier] >= _PER_TIER_CAPS.get(tier, 5):
            stats["removed_tier_cap"] += 1
            logger.debug("FILTER tier_cap       %s (tier: %s)", r["url"], tier)
            continue
        if len(capped) >= _TOTAL_CAP:
            stats["removed_total_cap"] += 1
            logger.debug("FILTER total_cap      %s", r["url"])
            continue
        tier_counts[tier] += 1
        capped.append(r)

    stats["output"] = len(capped)
    return capped, dict(stats)


# ---------------------------------------------------------------------------
# Subtask 5 — Body fetch + key-entity filter
# ---------------------------------------------------------------------------

_FETCH_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}
_ENTITY_MATCH_THRESHOLD = 80  # rapidfuzz partial_ratio minimum for a hit
_MIN_CONTENT_CHARS = 200       # trafilatura extractions below this are noise

# ── Title noise detection ────────────────────────────────────────────────────

_TITLE_NOISE_FRAGMENTS = (
    "need cookies", "cookie", "hauptnavigation", "navigation", "menu",
    "accept all", "privacy settings", "newsletter", "subscribe", "sign up",
    "log in", "login", "sign in",
)

def _is_noisy_title(title: str) -> bool:
    t = title.strip()
    if not t or len(t) < 5:
        return True
    t_lower = t.lower()
    if any(frag in t_lower for frag in _TITLE_NOISE_FRAGMENTS):
        return True
    # Single bare word (likely a nav label)
    if len(t.split()) == 1 and not any(c.isdigit() for c in t):
        return True
    return False


def _fallback_title(html: str, url: str) -> str:
    """Try og:title → twitter:title → first <h1> → URL slug."""
    # og:title (two attribute orderings)
    for pat in (
        r'<meta[^>]+property=["\']og:title["\'][^>]+content=["\']([^"\']{5,})["\']',
        r'<meta[^>]+content=["\']([^"\']{5,})["\'][^>]+property=["\']og:title["\']',
    ):
        m = re.search(pat, html, re.IGNORECASE)
        if m:
            return m.group(1).strip()
    # twitter:title
    for pat in (
        r'<meta[^>]+name=["\']twitter:title["\'][^>]+content=["\']([^"\']{5,})["\']',
        r'<meta[^>]+content=["\']([^"\']{5,})["\'][^>]+name=["\']twitter:title["\']',
    ):
        m = re.search(pat, html, re.IGNORECASE)
        if m:
            return m.group(1).strip()
    # First <h1>
    m = re.search(r"<h1[^>]*>([^<]{5,})</h1>", html, re.IGNORECASE)
    if m:
        return re.sub(r"\s+", " ", m.group(1)).strip()
    # URL slug
    path = urlparse(url).path.rstrip("/").split("/")[-1]
    slug = re.sub(r"[-_]", " ", re.sub(r"\.\w+$", "", path)).strip().title()
    return slug or url

# ── published_at sanity check ────────────────────────────────────────────────

_DATE_FLOOR = datetime(2010, 1, 1, tzinfo=timezone.utc)

def _sanitize_date(date_str: str | None) -> str | None:
    if not date_str:
        return None
    try:
        dt = _parse_partial_date(date_str)
        if dt < _DATE_FLOOR or dt > datetime.now(tz=timezone.utc) + timedelta(days=365):
            return None
        return date_str
    except Exception:
        return None


def _entity_match(body: str, key_entities: list) -> bool:
    """Return True if any key_entity name fuzzy-matches the body (partial_ratio ≥ threshold)."""
    body_lower = body.lower()
    for entity in key_entities:
        if fuzz.partial_ratio(entity.name.lower(), body_lower) >= _ENTITY_MATCH_THRESHOLD:
            return True
    return False


async def _fetch_one(client: httpx.AsyncClient, url: str, cache) -> dict | None:
    """Fetch a single URL, extract text + metadata via trafilatura. Returns None on any failure."""
    cache_key = f"fetch:{fetch_cache_key(url)}"
    cached = cache.get(cache_key)
    if cached is not None:
        logger.debug("Fetch cache hit: %s", url[:80])
        return cached

    try:
        resp = await client.get(url, follow_redirects=True, timeout=15.0)
        resp.raise_for_status()
        html = resp.text
    except Exception as exc:
        logger.warning("Fetch failed %s: %s", url[:80], exc)
        return None

    text = trafilatura.extract(html, include_comments=False, include_tables=True)
    if not text:
        logger.warning("trafilatura returned empty: %s", url[:80])
        return None

    meta = trafilatura.extract_metadata(html, default_url=url)
    raw_title = (meta.title or "").strip() if meta else ""
    if _is_noisy_title(raw_title):
        raw_title = _fallback_title(html, url)
    result = {
        "content": text,
        "published_at_page": meta.date if meta else None,
        "meta_title": raw_title,
        "fetched_at": datetime.now(tz=timezone.utc).isoformat(),
    }
    cache.set(cache_key, result)
    return result


async def _fetch_all(candidates: list[dict]) -> list[tuple[dict, dict | None]]:
    cache = get_cache()
    async with httpx.AsyncClient(headers=_FETCH_HEADERS) as client:
        tasks = [_fetch_one(client, r["url"], cache) for r in candidates]
        results = await asyncio.gather(*tasks)
    return list(zip(candidates, results))


def fetch_and_filter_bodies(
    candidates: list[dict],
    plan: Plan,
) -> tuple[list[dict], dict]:
    """
    Fetch body content for all candidates, then apply key-entity fuzzy filter.
    Returns (enriched_list, stats_dict).
    """
    pairs = asyncio.run(_fetch_all(candidates))

    stats: dict[str, int] = defaultdict(int)
    stats["input"] = len(candidates)
    entity_kills: list[str] = []
    enriched: list[dict] = []

    for candidate, fetch_result in pairs:
        url = candidate["url"]

        if fetch_result is None:
            stats["removed_fetch_failed"] += 1
            continue

        content = fetch_result["content"]

        if len(content) < _MIN_CONTENT_CHARS:
            stats["removed_too_short"] += 1
            logger.info("Skip (content %d chars): %s", len(content), url[:80])
            continue

        # Tier 1 sources were targeted via site:-scoped queries for this exact event;
        # entity filter would produce false negatives on technical primary docs.
        if candidate.get("retrieval_tier") != 1:
            if not _entity_match(content, plan.key_entities):
                stats["removed_entity_mismatch"] += 1
                entity_kills.append(url)
                logger.info("Skip (entity mismatch): %s", url[:80])
                continue

        # Prefer trafilatura's date over Tavily's; fall back to whatever Tavily gave us
        pub = _sanitize_date(
            fetch_result.get("published_at_page") or candidate.get("published_at")
        )
        title = fetch_result.get("meta_title") or candidate.get("title", "")

        enriched.append({
            **candidate,
            "content": content,
            "published_at": pub,
            "title": title,
            "fetched_at": fetch_result["fetched_at"],
        })

    stats["output"] = len(enriched)
    stats["_entity_kills"] = entity_kills  # for reporting; stripped before return
    return enriched, dict(stats)


# ---------------------------------------------------------------------------
# Subtask 6 — Near-duplicate detection (MinHash / Jaccard)
# ---------------------------------------------------------------------------

_MINHASH_NUM_PERM = 128          # permutations; balances accuracy vs. speed
_NEAR_DUP_THRESHOLD = 0.85       # Jaccard ≥ 0.85 → same content


def _minhash(text: str) -> MinHash:
    """Build a MinHash from 3-gram shingles of the text."""
    mh = MinHash(num_perm=_MINHASH_NUM_PERM)
    words = text.lower().split()
    for i in range(max(1, len(words) - 2)):
        shingle = " ".join(words[i : i + 3])
        mh.update(shingle.encode("utf-8"))
    return mh


def deduplicate_near_duplicates(sources: list[dict]) -> tuple[list[dict], dict]:
    """
    Cluster sources by MinHash Jaccard similarity and keep one representative
    per cluster: prefer higher credibility tier, then more recent published_at.

    Returns (deduped_list, stats_dict).
    """
    if not sources:
        return [], {"input": 0, "output": 0, "removed_near_dup": 0}

    minhashes = [_minhash(s["content"]) for s in sources]

    # Union-Find for clustering
    parent = list(range(len(sources)))

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a: int, b: int) -> None:
        parent[find(a)] = find(b)

    for i in range(len(sources)):
        for j in range(i + 1, len(sources)):
            if minhashes[i].jaccard(minhashes[j]) >= _NEAR_DUP_THRESHOLD:
                union(i, j)
                logger.debug(
                    "Near-dup pair (j=%.2f): %s  ~  %s",
                    minhashes[i].jaccard(minhashes[j]),
                    sources[i]["url"][:60],
                    sources[j]["url"][:60],
                )

    # Group by cluster root
    clusters: dict[int, list[int]] = defaultdict(list)
    for idx in range(len(sources)):
        clusters[find(idx)].append(idx)

    # Pick representative: best credibility tier, then most recent date
    kept: list[dict] = []
    for members in clusters.values():
        best = min(
            members,
            key=lambda i: (
                _TIER_RANK.get(sources[i].get("credibility_tier", "tier_3_media"), 5),
                _date_sort_key(sources[i].get("published_at")),
            ),
        )
        kept.append(sources[best])

    removed = len(sources) - len(kept)
    stats = {"input": len(sources), "removed_near_dup": removed, "output": len(kept)}
    if removed:
        logger.info("Near-dup dedup: %d → %d (removed %d)", len(sources), len(kept), removed)
    return kept, stats


# ---------------------------------------------------------------------------
# run() — full Stage B pipeline
# ---------------------------------------------------------------------------

def _make_slug(text: str) -> str:
    clean = re.sub(r"[^a-z0-9\s]", "", text.lower())
    return "-".join(clean.split()[:6])


def _save(output: SourcesOutput, input_sentence: str) -> None:
    slug = _make_slug(input_sentence)
    out_dir = OUTPUTS_DIR / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "sources.json"
    path.write_text(
        json.dumps(output.model_dump(), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    logger.info("Stage B → %s", path)


def run(plan: Plan, input_sentence: str, tavily: TavilyClient | None = None) -> SourcesOutput | None:
    if tavily is None:
        tavily = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])

    tier1 = discover_tier1_urls(plan, tavily)
    tier2 = search_tier2(plan, tavily)
    filtered, filter_stats = filter_urls(tier1 + tier2, plan)
    logger.info("Filter: %s", filter_stats)

    enriched, fetch_stats = fetch_and_filter_bodies(filtered, plan)
    logger.info("Fetch: %s", {k: v for k, v in fetch_stats.items() if not k.startswith("_")})

    if not enriched:
        logger.warning("Stage B: no sources after fetch+entity filter for: %s", plan.normalized_title)
        return None

    enriched, dedup_stats = deduplicate_near_duplicates(enriched)
    logger.info("Near-dup: %s", dedup_stats)

    sources = [
        Source(
            id=f"src_{i:03d}",
            url=r["url"],
            title=r.get("title", ""),
            domain=r.get("domain") or extract_domain(r["url"]),
            fetched_at=r["fetched_at"],
            published_at=r.get("published_at"),
            credibility_tier=r["credibility_tier"],
            retrieval_tier=r["retrieval_tier"],
            content=r["content"],
        )
        for i, r in enumerate(enriched, start=1)
    ]
    output = SourcesOutput(sources=sources)
    _save(output, input_sentence)
    return output


def _date_sort_key(date_str: str | None) -> str:
    """Sort key for published_at: more recent dates sort first (reverse=False via negation trick).
    We prefix with '0' for known dates (inverted via string complement) and '1' for unknown."""
    if not date_str:
        return "1"
    # Negate lexicographic order: replace each digit d with (9-d)
    negated = "".join(str(9 - int(c)) if c.isdigit() else c for c in date_str)
    return "0" + negated


if __name__ == "__main__":
    import sys
    from collections import Counter
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    _INPUT = "OpenAI rolled out GPT-5.5 Instant as the default model in ChatGPT in May 2026."
    plan_path = OUTPUTS_DIR / "openai-rolled-out-gpt55-instant-as" / "plan.json"
    plan = Plan.model_validate_json(plan_path.read_text(encoding="utf-8"))

    tavily = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])

    # Run fetch pipeline with detailed instrumentation
    tier1 = discover_tier1_urls(plan, tavily)
    tier2 = search_tier2(plan, tavily)
    filtered, filter_stats = filter_urls(tier1 + tier2, plan)

    print(f"\n=== Post-filter ({filter_stats['output']} candidates) ===")
    for k, v in filter_stats.items():
        if v:
            print(f"  {k}: {v}")

    # Fetch with per-source status tracking
    pairs = asyncio.run(_fetch_all(filtered))

    print(f"\n=== Fetch status ({len(filtered)} URLs) ===")
    fetch_ok, fetch_fail = 0, 0
    for cand, result in pairs:
        status = "OK   " if result else "FAIL "
        print(f"  {status} {cand['url'][:90]}")
        if result:
            fetch_ok += 1
        else:
            fetch_fail += 1
    print(f"  → {fetch_ok} OK, {fetch_fail} failed")

    # Entity filter (mirrors fetch_and_filter_bodies logic including Tier 1 bypass)
    cache = get_cache()
    enriched_list: list[dict] = []
    entity_kills: list[str] = []
    too_short_kills: list[str] = []
    pub_reparsed = 0
    for cand, result in pairs:
        if result is None:
            continue
        content = result["content"]
        if len(content) < _MIN_CONTENT_CHARS:
            too_short_kills.append(cand["url"])
            continue
        is_tier1 = cand.get("retrieval_tier") == 1
        if not is_tier1 and not _entity_match(content, plan.key_entities):
            entity_kills.append(cand["url"])
            continue
        pub = result.get("published_at_page") or cand.get("published_at")
        if result.get("published_at_page"):
            pub_reparsed += 1
        title = result.get("meta_title") or cand.get("title", "")
        enriched_list.append({
            **cand,
            "content": content,
            "published_at": pub,
            "title": title,
            "fetched_at": result["fetched_at"],
        })

    print(f"\n=== Entity filter kills ({len(entity_kills)}) ===")
    for url in entity_kills:
        print(f"  {url[:90]}")
    if too_short_kills:
        print(f"  [too short: {', '.join(u[:60] for u in too_short_kills)}]")

    print(f"\n=== published_at re-parse ===")
    print(f"  trafilatura date found: {pub_reparsed}/{fetch_ok}")

    print(f"\n=== Content length distribution ({len(enriched_list)} sources) ===")
    for r in enriched_list:
        chars = len(r["content"])
        bar = "#" * min(chars // 200, 40)
        print(f"  {chars:6d}c  {bar}  {r['url'][:60]}")

    # Near-dup dedup
    deduped, dedup_stats = deduplicate_near_duplicates(enriched_list)
    print(f"\n=== Near-duplicate dedup ===")
    print(f"  {dedup_stats['input']} → {dedup_stats['output']} (removed {dedup_stats['removed_near_dup']})")

    # Save via run() and show metadata table
    output = run(plan, _INPUT, tavily)
    if output:
        print(f"\n=== sources.json metadata ({len(output.sources)} sources) ===")
        print(f"  {'id':8s} {'tier':20s} {'pub_at':12s} {'domain'}")
        print(f"  {'-'*8} {'-'*20} {'-'*12} {'-'*40}")
        for s in output.sources:
            print(f"  {s.id:8s} {s.credibility_tier:20s} {s.published_at or 'None':12s} {s.domain}")
